from agents import (
    Agent
)

from module.constants import (
    DEFAULT_LLM
)


REPORT_AGENT_INSTRUCTIONS = f"""
YOUR TASK IS TO CURATE A REPORT OUT OF THE DETAILS THAT YOUR FELLOW AGENTS CURATED
OUT OF A WEB SEARCH OVER INPUT TOPIC AND QUESTIONS. ENSURE THAT THE OUTPUT IS NOT 
IN THE MARKDOWN FORM. MAKE SURE TO GROUP DETAILS PROPERLY AND AVOID REPETITION OF
THE CONTENT. YOU ARE NOT ALLOWED TO ADD ANY MORE CONTENT YOURSELF. RATHER JUST
USE WHAT IS PROVIDED TO YOU.
"""

report_generator_agent = Agent(
    name = "report agent",
    model=DEFAULT_LLM,
    instructions=REPORT_AGENT_INSTRUCTIONS
)